# Project information
site_name: 'Pact Developer Tutorials'

site_description: 'Pact Developer Tutorials'
site_author: 'Kadena'
# site_url: 'URL GOES HERE'

# Repository
repo_name: 'kadena-io/pact'
repo_url: 'https://github.com/kadena-io/pact'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Kadena'

    # Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
  font:
    text: 'Helvetica'
    code: 'Helvetica'
  favicon: 'assets/images/logo.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kadena-io'
    - type: 'twitter'
      link: 'https://twitter.com/kadena_io'

extra:
  disqus: 'joenyzio'

#google_analytics:
  #- 'CODE HERE'
  #- 'auto'
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

nav:
- Home: 'index.md'
        
- Beginner:
        # - 'Welcome to Pact': './beginner/introduction-to-pact.md'
        # - 'Standard Library': './beginner/pact-standard-library.md'
        - 'Pact Online Editor': './beginner/pact-online-editor.md'
        # - 'Hello World': './beginner/hello-world-with-pact.md'
        # - 'Functions': './beginner/pact-functions.md'
        # - 'Modules': './beginner/pact-modules.md'
        # - 'Keysets': './beginner/pact-keysets.md'
        # - 'Schemas and Tables': './beginner/pact-schemas-and-tables.md'
        # - 'Accounts and Transfers': './beginner/pact-accounts-and-transfers.md'
        # - 'Contract Interaction': './beginner/pact-contract-interaction.md'
        # - 'Atom SDK': './beginner/atom-sdk.md'
        # - 'Testing in the SDK': './beginner/testing-in-the-sdk.md'
        # - 'Pact and Javascript': './beginner/pact-and-javascript.md'
        # - 'Series Review': './beginner/series-review.md'
        
       