# Project information
site_name: 'Pact Developer Tutorials'

site_description: 'Pact Developer Tutorials'
site_author: 'Kadena'
# site_url: 'pactlang.org'

# Repository
repo_name: 'kadena-io/pact'
repo_url: 'https://github.com/kadena-io/pact'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Kadena'

    # Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
  font:
    text: 'Helvetica'
    code: 'Helvetica'
  favicon: 'assets/images/logo.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kadena-io'
    - type: 'twitter'
      link: 'https://twitter.com/kadena_io'

google_analytics:
  - 'UA-127512784-3'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

nav:
- Beginner:
        - '1. Welcome to Pact': './beginner/welcome-to-pact.md'
        - '2. Online Editor': './beginner/online-editor.md'
        - '3. Hello World': './beginner/hello-world-with-pact.md'
        - '4. Language Basics': './beginner/pact-language-basics.md'
        - '5. Modules': './beginner/pact-modules.md'
        - '6. Keysets': './beginner/pact-keysets.md'
        - '7. Schemas and Tables': './beginner/pact-schemas-and-tables.md'
        - '8. Atom SDK': './beginner/pact-on-atom-sdk.md'
        - '9. Accounts and Transfers': './beginner/pact-accounts-and-transfers.md'
        - '10. Contract Interaction': './beginner/contract-interaction.md'
        - '11. Project: Rotatable Wallet': './beginner/project-rotatable-wallet.md'
        - '12. Project: Loans': './beginner/project-loans.md'
        - '13. Test in the SDK': './beginner/testing-pact-code-in-the-sdk.md'

- Intermediate:
        # - 'Coming Soon': './intermediate/coming-soon.md'
        - '1. Deploy to a Local Server': './intermediate/deploy-local-server.md'
        - '2. Pact and Javascript': './intermediate/pact-and-javascript.md'
        - '3. Safety Using Control Flow': './intermediate/safety-with-pact.md'
        - '4. Interfaces with Pact': './intermediate/interfaces-with-pact.md'
- Advanced:
        - 'Coming Soon': './advanced/coming-soon.md'
