# Project information
site_name: 'Pact Developer Tutorials'

site_description: 'Pact Developer Tutorials'
site_author: 'Kadena'
# site_url: 'pactlang.org'

# Repository
repo_name: 'kadena-io/pact'
repo_url: 'https://github.com/kadena-io/pact'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Kadena'

    # Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Cyan'
    accent: 'Cyan'
  feature:
    tabs: true
  font:
    text: 'Helvetica'
    code: 'Helvetica'
  favicon: 'assets/images/logo.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kadena-io'
    - type: 'twitter'
      link: 'https://twitter.com/kadena_io'

google_analytics:
  - 'UA-127512784-3'
  - 'auto'
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true

nav:    
- Beginner:
        - 'Welcome to Pact': './beginner/welcome-to-pact.md'        
        - 'Online Editor': './beginner/online-editor.md'
        - 'Hello World': './beginner/hello-world-with-pact.md'
        - 'Language Basics': './beginner/pact-language-basics.md'
        - 'Modules': './beginner/pact-modules.md'
        - 'Keysets': './beginner/pact-keysets.md'
        - 'Schemas and Tables': './beginner/pact-schemas-and-tables.md'
        - 'Accounts and Transfers': './beginner/pact-accounts-and-transfers.md'
        # - 'Contract Interaction': './beginner/pact-contract-interaction.md'
        - 'Atom SDK': './beginner/pact-on-atom-sdk.md'
        - 'Test in the SDK': './beginner/testing-pact-code-in-the-sdk.md'
        - 'Project: Rotatable Wallet': './beginner/project-rotatable-wallet.md'
        - 'Project: Loans': './beginner/project-loans.md'
        
      
- Intermediate:
        - 'Coming Soon': './intermediate/coming-soon.md'        
- Advanced:
        - 'Coming Soon': './advanced/coming-soon.md'        
        
       